version: '3.9'

services:
  filetransfermanager.service:
    image: ${DOCKER_REGISTRY-}filetransfermanagerapi
    container_name: "filetransfermanager.api"
    restart: "always"
    build:
      context: .
      dockerfile: src/FileTransferManager.Api/Dockerfile
    ports:
      - "4005:8080" 
#      - "4005:8081"
    environment:
      - Logging__LogLevel__Default=Warning
      - Logging__LogLevel__Microsoft.AspNetCore=Warning

      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTPS_PORTS=4005
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/ssl/aspnetapp.pfx

      - Keycloak__Authority=http://host.docker.internal:4000/realms/inventory_management_realm
      - Keycloak__Audience=InventoryManagementClient
      - Keycloak__KeycloakResourceUrl=http://host.docker.internal:4000/realms/inventory_management_realm/authz/protection/resource_set/
      - Keycloak__ClientCredentialsTokenAddress=http://host.docker.internal:4000/realms/inventory_management_realm/protocol/openid-connect/token
    volumes:
      - c:\wwwroot:/app/wwwroot
      - ./src/FileTransferManager.Api/ssl:/src/ssl
      - ./src/FileTransferManager.Api/ssl/docker-host.crt:/etc/x509/https/docker-host.crt                   # host.docker.internal ssl
      - ./src/FileTransferManager.Api/ssl/docker-host.key:/etc/x509/https/docker-host.key                   # host.docker.internal ssl
    network_mode: bridge
