version: '3.9'

services:
  filetransfermanager.service:
    image: ${DOCKER_REGISTRY-}filetransfermanagerapi
    container_name: "filetransfermanager.api"
    restart: "always"
    build:
      context: .
      dockerfile: src/FileTransferManager.Api/Dockerfile
    ports:
      - "4005:80"
    volumes:
      - c:\wwwroot:/app/wwwroot
    network_mode: bridge
